export const API_ROUTES = {
	HOST: 'https://api.up-development.ru',
	BASE_URL: 'https://api.up-development.ru/api',
	GET_ALL_ADMINISTRATORS: '/administrators',
	MEDIA: '/media',
	AUTH: {
		LOGIN: '/authorization/sign-in',
		REGISTER: '/authorization/sign-up',
		VERIFY: '/verification',
		EDIT_PROFILE: (id: string) => `authorization/edit-profile/${id}`,
		DELETE_BY_ID: (id: string) => `authorization/delete/${id}`,
	},
	BANNER: {
		INDEX: '/banner',
		GET_BANNERS: '/banner/get-all',
		CREATE_BANNER: '/banner/create-banner',
		UPDATE_BANNER: '/banner/update-banner',
		DELETE_BANNER: (id: string) => `/banner/delete-banner/${id}`,
		UPDATE_POSITION: '/banner/update-position',
	},
	EVENTS: {
		INDEX: '/events',
		GET_BY_ID: (id: string) => `/events/get-by-id/${id}`,
		CREATE_EVENT: '/events/create-event',
		UPDATE_EVENT: (id: string) => `/events/update-event/${id}`,
		DELETE_EVENT: (id: string) => `/events/delete-event/${id}`,
	},
	PRODUCTS: {
		INDEX: '/products',
		CREATE_PRODUCT: '/products/create-product',
		UPDATE_PRODUCT: (id: string) => `/products/update-product/${id}`,
		DELETE_PRODUCT: (id: string) => `/products/delete-product/${id}`,
	},
	CATEGORIES: {
		INDEX: '/products/categories',
		CREATE_CATEGORY: '/products/create-category',
		UPDATE_CATEGORY: (id: string) => `/products/update-category/${id}`,
		DELETE_CATEGORY: (id: string) => `/products/delete-category/${id}`,
	},
} as const
